### ISSUE TITLE
Integrate Google Analytics data

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#96]
Hi,
I tried to integrate Google Analytics data, however the below error displayed.

![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/26494691-df75-41bb-b767-625e62fbeb01)

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan,

Can you provide some information:
1. Have you used SaaS or an open-source 
2. If you use SaaS, could you please provide me with the organization name?

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan,
Can you provide some information:
1. Which version are you using, Saas or open-source version?
2. If you use SaaS, could you please provide me with the organization name?

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12 ,

1. First, I tried to integrate google analytics using open-source version. But it displays the below error.

    ![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/700d39f0-a21f-4994-a1aa-204daf506cb5)

    Then, I tried integrating using Saas version. `not found connection org 216 error` shows on Saas version.
2. The Organization name is **Ewall**.

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan,

+ In Saas Version, you must setup data-warehouse before integrate Google Analytics.
+ In OSS version, you must update config google OAuth, flow step below: 
1. Create google credentials in [here](https://developers.google.com/workspace/guides/create-credentials#oauth-client-id). Copy client id and client secret for next step.
2. Update google configure in `rocket-bi-server/conf/product.conf`:
```md
google {
  gg_client_id = "" <- here
  gg_client_secret = "" <- here 
  server_encoded_url = "https://accounts.google.com/o/oauth2/token"
  redirect_uri = "https%3A%2F%2Fhello.rocket.bi" <- here
}
....
google_ads_api {
  gg_client_id = "" <- here
  gg_client_secret = "" <- here
  server_encoded_url = "https://accounts.google.com/o/oauth2/token"
  redirect_uri = "http%3A%2F%2Flocalhost%3A8080&" <- here
  developer_token = ""
  metadata_uri = "https://gaql-query-builder.uc.r.appspot.com/schemas/v12"
}
```
3. restart service and check again

**Comment by tvc12** [comment]
Update `rocket-bi-web/public/config/production.js`:

```md
  //Third party ingestion config
  GOOGLE_CLIENT_ID: '', <-here 
  GOOGLE_API_KEY: '', <- here
```

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12 ,
I have installed rocket bi using docker image. Followed the below steps.
https://github.com/datainsider-co/rocket-bi/tree/main/docker
I can't find any directory except logs inside rocket-bi-server directory.

**Comment by tvc12** [comment]
1. Copy https://github.com/datainsider-co/rocket-bi/blob/main/rocket-bi-server/conf/production.conf to `rocket-bi-server/conf/production.conf`
2. Copy folder https://github.com/datainsider-co/rocket-bi/tree/main/rocket-bi-web/public/config to `rocket-bi-web/public/config`
3. Update file `docker/docker-compose.yml`
```yml
  rocket-bi-server:
    image: datainsiderco/rocket-bi-server:main
    container_name: rocket-bi-server
    restart: always
    environment:
      NAME: rocket-bi-server
      MODE: production
    volumes:
      - ./rocket-bi-server/conf:/app/conf # <- new
      - ./rocket-bi-server/logs:/app/logs
      - biservice-mapdata:/app/mapdata
    depends_on:
      - mysql
      - ssdb

  rocket-bi-web:
    image: datainsiderco/rocket-bi-web:main
    container_name: rocket-bi-web
    restart: always
    volumes:  # <-new
      - ./rocket-bi-web/public/config:/app/config # <-new
```
